# Site settings
title: Blossoms
email: Klagender@gmail.com
description: 

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://klagender.github.io" # the base hostname & protocol for your site

# Trivial
timezone: CN

# Build settings
markdown: kramdown
permalink: none
pygments: true
paginate_path: "/Ethos/page:5/"
paginate_path: "/Pathos/page:5/"
paginate_path: "/Logos/page:5/"
